sudo: false
language: python
python:
  - "2.7"
  - "3.6"
cache: apt
addons:
   apt:
      packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - #conda update --yes conda
install:
  - conda create -y --name travis python=$TRAVIS_PYTHON_VERSION && source activate travis
  - python -m pip install -r requirements.txt	
  - python -m pip install pytest-cov python-coveralls mock
  - python -m pip install --upgrade coverage
script:
  - make test
after_success:
  - coveralls
